package net.thucydides.model.domain;

import net.thucydides.model.requirements.model.Requirement;

import java.util.*;
import java.util.function.Function;
import java.util.function.Supplier;

/**
 * A cache of the requirements used when the reports are generated.
 * <p>
 * Reports are generated by a pool of threads, and each of those threads looks up the requirements
 * of the test outcome it is reporting on, so every field in this cache is read and written by
 * several threads at a time. Readers are served immutable snapshots, which they can iterate over
 * safely while another thread is updating the cache.
 */
public class RequirementCache {

    private final Object requirementsLock = new Object();
    private final Object flattenedRequirementsLock = new Object();
    private final Object pathIndexLock = new Object();
    private final Object tagIndexLock = new Object();

    private volatile List<Requirement> requirements;

    /** Guarded by flattenedRequirementsLock. */
    private final List<Requirement> flattenedRequirements = new ArrayList<>();
    /** Guarded by flattenedRequirementsLock; used to avoid scanning the list on each update. */
    private final Set<Requirement> flattenedRequirementsSet = new HashSet<>();
    /** An immutable snapshot of flattenedRequirements, published for readers. */
    private volatile List<Requirement> flattenedRequirementsSnapshot = Collections.emptyList();

    /** Guarded by pathIndexLock. */
    private final Map<String, Requirement> requirementsPathIndex = new HashMap<>();
    /** An immutable snapshot of requirementsPathIndex, published for readers. */
    private volatile Map<String, Requirement> requirementsPathIndexSnapshot = Collections.emptyMap();

    /**
     * Guarded by tagIndexLock. A null value means "we have already looked for this tag and found
     * nothing", so this map needs to support null values.
     */
    private final Map<TestTag, Requirement> requirementsByTag = new HashMap<>();

    private RequirementCache() {
    }

    public void clear() {
        synchronized (requirementsLock) {
            requirements = null;
        }
        synchronized (flattenedRequirementsLock) {
            flattenedRequirements.clear();
            flattenedRequirementsSet.clear();
            flattenedRequirementsSnapshot = Collections.emptyList();
        }
        synchronized (pathIndexLock) {
            requirementsPathIndex.clear();
            requirementsPathIndexSnapshot = Collections.emptyMap();
        }
        synchronized (tagIndexLock) {
            requirementsByTag.clear();
        }
    }

    public static RequirementCache getInstance() {
        return SingletonHelper.INSTANCE;
    }

    /**
     * Return the cached requirements, loading them with the supplied factory the first time they
     * are asked for. Loading the requirements means reading every test outcome from disk, so the
     * factory is only ever called once.
     */
    public List<Requirement> getRequirements(Supplier<List<Requirement>> requirementFactory) {
        List<Requirement> cachedRequirements = requirements;
        if (cachedRequirements == null) {
            synchronized (requirementsLock) {
                cachedRequirements = requirements;
                if (cachedRequirements == null) {
                    cachedRequirements = requirementFactory.get();
                    requirements = cachedRequirements;
                }
            }
        }
        return cachedRequirements;
    }

    public void indexRequirements(Map<PathElements, Requirement> requirementsByPath) {
        synchronized (pathIndexLock) {
            requirementsByPath.forEach(
                    (path, requirement) -> requirementsPathIndex.put(requirement.getPath(), requirement)
            );
            requirementsPathIndexSnapshot = Collections.unmodifiableMap(new HashMap<>(requirementsPathIndex));
        }
    }

    public Map<String, Requirement> getRequirementsPathIndex() {
        return requirementsPathIndexSnapshot;
    }

    public Requirement getRequirementsByTag(TestTag testTag, Function<TestTag, Requirement> requirementFinder) {
        return getRequirementsByTag(testTag, requirementFinder, false);
    }

    public Requirement getRequirementsByTag(TestTag testTag, Function<TestTag, Requirement> requirementFinder, boolean forceLoad) {
        synchronized (tagIndexLock) {
            if (requirementsByTag.containsKey(testTag) && !(null == requirementsByTag.get(testTag) && forceLoad)) {
                return requirementsByTag.get(testTag);
            }
        }
        // Looking a tag up means scanning the requirements, so it is done outside the lock. Two
        // threads looking for the same tag at the same time will find the same requirement.
        Requirement matchingRequirement = requirementFinder.apply(testTag);
        synchronized (tagIndexLock) {
            requirementsByTag.put(testTag, matchingRequirement);
            return matchingRequirement;
        }
    }

    private static class SingletonHelper {
        private static final RequirementCache INSTANCE = new RequirementCache();
    }

    public void updateFlattenedRequirements(List<Requirement> requirements) {
        synchronized (flattenedRequirementsLock) {
            addToFlattenedRequirements(requirements);
        }
    }

    /**
     * Return the flattened requirements, working them out with the supplied factory if they have
     * not been cached yet.
     */
    public List<Requirement> getFlattenedRequirements(Supplier<List<Requirement>> flattenedRequirementFactory) {
        List<Requirement> snapshot = flattenedRequirementsSnapshot;
        if (snapshot.isEmpty()) {
            synchronized (flattenedRequirementsLock) {
                if (flattenedRequirements.isEmpty()) {
                    addToFlattenedRequirements(flattenedRequirementFactory.get());
                }
                snapshot = flattenedRequirementsSnapshot;
            }
        }
        return snapshot;
    }

    public List<Requirement> getRequirements() {
        return requirements;
    }

    public List<Requirement> getFlattenedRequirements() {
        return flattenedRequirementsSnapshot;
    }

    /** Must be called while holding flattenedRequirementsLock. */
    private void addToFlattenedRequirements(List<Requirement> requirements) {
        boolean updated = false;
        for (Requirement requirement : requirements) {
            if (flattenedRequirementsSet.add(requirement)) {
                flattenedRequirements.add(requirement);
                updated = true;
            }
        }
        if (updated) {
            flattenedRequirementsSnapshot = Collections.unmodifiableList(new ArrayList<>(flattenedRequirements));
        }
    }
}
