package net.thucydides.model.domain;

import net.thucydides.model.requirements.model.Requirement;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Reports are generated by a pool of threads (see Reporter), and every one of them reads the
 * requirements from the shared RequirementCache singleton. These tests check that the cache
 * can be read and updated from several threads at once.
 */
class RequirementCacheConcurrencyTest {

    private static final int THREADS = 8;

    private ExecutorService executor;

    @BeforeEach
    void clearTheCache() {
        RequirementCache.getInstance().clear();
        executor = Executors.newFixedThreadPool(THREADS);
    }

    @AfterEach
    void shutDownTheExecutor() throws InterruptedException {
        executor.shutdownNow();
        executor.awaitTermination(10, TimeUnit.SECONDS);
        RequirementCache.getInstance().clear();
    }

    private List<Requirement> requirements(String prefix, int count) {
        return IntStream.range(0, count)
                .mapToObj(index -> Requirement.named(prefix + "-" + index)
                        .withType("feature")
                        .withNarrative("Narrative " + index)
                        .withPath(prefix + "/" + index))
                .collect(Collectors.toList());
    }

    @Test
    @DisplayName("Requirements should only be loaded once, however many threads ask for them")
    void requirementsShouldBeLoadedOnlyOnce() throws Exception {
        AtomicInteger timesLoaded = new AtomicInteger();

        // Loading the requirements means reading every test outcome from disk, so it is slow.
        List<Requirement> loadedRequirements = requirements("loaded", 10);
        CountDownLatch allThreadsReady = new CountDownLatch(THREADS);
        CountDownLatch go = new CountDownLatch(1);

        List<Future<List<Requirement>>> results = new ArrayList<>();
        for (int thread = 0; thread < THREADS; thread++) {
            results.add(executor.submit(() -> {
                allThreadsReady.countDown();
                go.await();
                return RequirementCache.getInstance().getRequirements(() -> {
                    timesLoaded.incrementAndGet();
                    sleepFor(50);
                    return loadedRequirements;
                });
            }));
        }

        allThreadsReady.await(10, TimeUnit.SECONDS);
        go.countDown();

        for (Future<List<Requirement>> result : results) {
            assertThat(result.get(30, TimeUnit.SECONDS)).isEqualTo(loadedRequirements);
        }
        assertThat(timesLoaded.get()).isEqualTo(1);
    }

    @Test
    @DisplayName("Flattened requirements should never contain null values while they are being cached")
    void flattenedRequirementsShouldNeverContainNulls() throws Exception {
        // Each round replays what happens at the start of report generation: one thread fills the
        // cache while the report threads read it.
        for (int round = 0; round < 1000; round++) {
            RequirementCache.getInstance().clear();

            List<Requirement> requirements = requirements("round" + round + "-requirement", 400);
            CountDownLatch go = new CountDownLatch(1);
            List<Future<?>> results = new ArrayList<>();

            results.add(executor.submit(() -> {
                go.await();
                RequirementCache.getInstance().updateFlattenedRequirements(requirements);
                return null;
            }));

            for (int thread = 0; thread < THREADS - 1; thread++) {
                results.add(executor.submit(() -> {
                    go.await();
                    for (int read = 0; read < 400; read++) {
                        assertThat(RequirementCache.getInstance().getFlattenedRequirements())
                                .doesNotContainNull();
                    }
                    return null;
                }));
            }

            go.countDown();
            for (Future<?> result : results) {
                result.get(60, TimeUnit.SECONDS);
            }
        }
    }

    @Test
    @DisplayName("Concurrent updates should not lose requirements")
    void concurrentUpdatesShouldNotLoseRequirements() throws Exception {
        int batchesPerThread = 20;
        int requirementsPerBatch = 50;

        CountDownLatch go = new CountDownLatch(1);
        List<Future<?>> results = new ArrayList<>();

        for (int thread = 0; thread < THREADS; thread++) {
            int threadNumber = thread;
            results.add(executor.submit(() -> {
                go.await();
                for (int batch = 0; batch < batchesPerThread; batch++) {
                    RequirementCache.getInstance()
                            .updateFlattenedRequirements(requirements("thread" + threadNumber + "-batch" + batch, requirementsPerBatch));
                }
                return null;
            }));
        }

        go.countDown();
        for (Future<?> result : results) {
            result.get(60, TimeUnit.SECONDS);
        }

        assertThat(RequirementCache.getInstance().getFlattenedRequirements())
                .doesNotContainNull()
                .hasSize(THREADS * batchesPerThread * requirementsPerBatch);
    }

    private static void sleepFor(long milliseconds) {
        try {
            Thread.sleep(milliseconds);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
    }
}
